steps:
  - id: 'Initialize Terraform'
    name: "hashicorp/terraform:1.0.0"
    entrypoint: 'sh'
    secretEnv: ['secret']
    args:
      - '-c'
      - |
        echo "*******************"
        echo "Terraform Init"
        echo "*******************"
        terraform init -backend-config="bucket=bucket-statefile" -backend-config="prefix=terraform/state" || exit 1

  - id: 'Validate Terraform'
    name: "hashicorp/terraform:1.0.0"
    entrypoint: 'sh'
    secretEnv: ['secret']
    args:
      - '-c'
      - |
        echo "*******************"
        echo "Terraform Validate"
        echo "*******************"
        terraform validate

  - id: 'Terraform Plan'
    name: "hashicorp/terraform:1.0.0"
    entrypoint: 'sh'
    secretEnv: ['secret']
    args:
      - '-c'
      - |
        echo "*******************"
        echo "Terraform Plan"
        echo "*******************"
        terraform plan

  - id: 'Terraform Apply'
    name: "hashicorp/terraform:1.0.0"
    entrypoint: 'sh'
    secretEnv: ['secret']
    args:
      - '-c'
      - |
        echo "*******************"
        echo "Terraform Apply"
        echo "*******************"
        terraform apply --auto-approve

  - id: 'Create Zip'
    name: "gcr.io/cloud-builders/gsutil"
    entrypoint: 'bash'
    secretEnv: ['secret']
    args:
      - '-c'
      - |
        zip -r source_repo.zip ./
        gsutil cp source_repo.zip gs://bucket-statefile/terraform/state/

availableSecrets:
  secretManager:
    - versionName: projects/549477020228/secrets/secret/versions/1
      env: "secret"
options:
  logging: CLOUD_LOGGING_ONLY
